#!/usr/bin/env bash
set -euo pipefail

SCRIPT_VERSION="1.0.0"

CLIPROXYAPI_REPO="router-for-me/CLIProxyAPI"
CPAQ_REPO="AllenReder/CLIProxyAPI-Quota-Inspector"

INSTALL_ROOT="${CLIPROXYAPI_INSTALL_ROOT:-$HOME/.local/share/cliproxyapi}"
BIN_DIR="${CLIPROXYAPI_BIN_DIR:-$HOME/.local/bin}"
CONFIG_DIR="${CLIPROXYAPI_CONFIG_DIR:-$HOME/.cli-proxy-api}"
APP_DIR="$INSTALL_ROOT/app"
CONFIG_PATH="${CLIPROXYAPI_APP_CONFIG_PATH:-$APP_DIR/config.yaml}"
SYSTEMD_USER_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
SERVICE_NAME="cliproxyapi.service"
SERVICE_PATH="$SYSTEMD_USER_DIR/$SERVICE_NAME"

DEFAULT_PORT="${CLIPROXYAPI_PORT:-8318}"
DEFAULT_API_KEY="${CLIPROXYAPI_API_KEY:-sk-my-secret-key}"
DEFAULT_MANAGEMENT_KEY="${CLIPROXYAPI_MANAGEMENT_KEY:-}"
FORCE_CONFIG="${CLIPROXYAPI_FORCE_CONFIG:-0}"

TMP_DIR="$(mktemp -d)"

cleanup() {
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

log() {
  printf '[install] %s\n' "$*"
}

fail() {
  printf '[install] ERROR: %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "Missing required command: $1"
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64)
      printf 'amd64'
      ;;
    aarch64|arm64)
      printf 'arm64'
      ;;
    *)
      fail "Unsupported architecture: $(uname -m)"
      ;;
  esac
}

fetch_release_asset_url() {
  local repo="$1"
  local asset_name="$2"
  local release_json

  release_json="$(curl -fsSL "https://api.github.com/repos/$repo/releases/latest")"

  printf '%s' "$release_json" | python3 -c '
import json
import sys

asset_name = sys.argv[1]
data = json.load(sys.stdin)

for asset in data.get("assets", []):
    if asset.get("name") == asset_name:
        print(asset["browser_download_url"])
        break
else:
    raise SystemExit(f"asset not found: {asset_name}")
' "$asset_name"
}

fetch_release_version() {
  local repo="$1"
  curl -fsSL "https://api.github.com/repos/$repo/releases/latest" | python3 -c '
import json
import sys

data = json.load(sys.stdin)
tag = data["tag_name"]
print(tag[1:] if tag.startswith("v") else tag)
'
}

random_secret() {
  if [ -n "$DEFAULT_MANAGEMENT_KEY" ]; then
    printf '%s' "$DEFAULT_MANAGEMENT_KEY"
    return
  fi

  openssl rand -hex 16
}

ensure_path_line() {
  local bashrc="$HOME/.bashrc"
  local line='export PATH="$HOME/.local/bin:$PATH"'

  touch "$bashrc"
  if ! grep -Fq "$line" "$bashrc"; then
    printf '\n%s\n' "$line" >> "$bashrc"
    log "Added ~/.local/bin to PATH in $bashrc"
  fi
}

render_config() {
  local target="$1"
  local api_key="$2"
  local management_key="$3"
  local port="$4"

  cat > "$target" <<EOF
# ============================================================
# CLIProxyAPI Linux Template
# Generated by CLIProxyAPI-Linux installer v$SCRIPT_VERSION
# OAuth auth files will be stored under ~/.cli-proxy-api
# ============================================================

host: "127.0.0.1"
port: $port

remote-management:
  allow-remote: false
  secret-key: "$management_key"
  disable-control-panel: false
  panel-github-repository: "https://github.com/router-for-me/Cli-Proxy-API-Management-Center"

auth-dir: "~/.cli-proxy-api"
api-keys:
  - "$api_key"

debug: false
logging-to-file: true
logs-max-total-size-mb: 200
error-logs-max-files: 20
usage-statistics-enabled: true
proxy-url: ""
passthrough-headers: true
nonstream-keepalive-interval: 30

request-retry: 3
max-retry-credentials: 0
max-retry-interval: 30

quota-exceeded:
  switch-project: true
  switch-preview-model: true
  antigravity-credits: true

routing:
  strategy: "round-robin"
  session-affinity: true
  session-affinity-ttl: "12h"

streaming:
  keepalive-seconds: 30
  bootstrap-retries: 3

oauth-model-alias:
  codex:
    - name: "gpt-5.4"
      alias: "claude-opus-4-5-20251101"
    - name: "gpt-5.4"
      alias: "claude-opus-4-1-20250805"
      fork: true
    - name: "gpt-5.4"
      alias: "claude-opus-4-20250514"
      fork: true
    - name: "gpt-5.4-mini"
      alias: "claude-sonnet-4-5-20250929"
      fork: true
    - name: "gpt-5.4-mini"
      alias: "claude-sonnet-4-6"
      fork: true
    - name: "gpt-5.4-mini"
      alias: "claude-sonnet-4-5"
      fork: true
    - name: "gpt-5.4-mini"
      alias: "claude-sonnet-4-20250514"
      fork: true
    - name: "gpt-5.3-codex"
      alias: "claude-haiku-4-5-20251101"
      fork: true
    - name: "gpt-5.3-codex"
      alias: "claude-3-5-haiku-20241022"
      fork: true
  antigravity:
    - name: "claude-sonnet-4-6"
      alias: "claude-opus-4-5-20251101"
    - name: "claude-sonnet-4-6"
      alias: "claude-opus-4-1-20250805"
      fork: true
    - name: "claude-sonnet-4-6"
      alias: "claude-opus-4-20250514"
      fork: true
    - name: "claude-sonnet-4-6"
      alias: "claude-sonnet-4-5-20250929"
      fork: true
    - name: "claude-sonnet-4-6"
      alias: "claude-sonnet-4-6"
      fork: true
    - name: "claude-sonnet-4-6"
      alias: "claude-sonnet-4-5"
      fork: true
    - name: "claude-sonnet-4-6"
      alias: "claude-sonnet-4-20250514"
      fork: true
    - name: "claude-sonnet-4-6"
      alias: "claude-haiku-4-5-20251101"
      fork: true
    - name: "claude-sonnet-4-6"
      alias: "claude-3-5-haiku-20241022"
      fork: true

payload:
  filter:
    - models:
        - name: "*"
          protocol: "antigravity"
      params:
        - "tools.#.function_declarations.#.parameters.propertyNames"
        - "tools.#.function_declarations.#.parameters.properties.*.propertyNames"
        - "tools.#.function_declarations.#.parameters.properties.*.items.properties.*.propertyNames"
        - "tools.#.function_declarations.#.parameters.properties.*.properties.*.propertyNames"
        - "tools.#.function_declarations.#.parameters.additionalProperties"
        - "tools.#.function_declarations.#.parameters.properties.*.additionalProperties"
        - "tools.#.function_declarations.#.parameters.properties.*.items.additionalProperties"
        - "tools.#.function_declarations.#.parameters.properties.*.items.properties.*.additionalProperties"
        - "tools.#.function_declarations.#.parameters.properties.*.patternProperties"
        - "tools.#.function_declarations.#.parameters.properties.*.items.properties.*.patternProperties"
        - "tools.#.function_declarations.#.parameters.\$schema"
        - "tools.#.function_declarations.#.parameters.\$id"
        - "tools.#.function_declarations.#.parameters.\$ref"
        - "tools.#.function_declarations.#.parameters.\$defs"
        - "tools.#.function_declarations.#.parameters.anyOf"
        - "tools.#.function_declarations.#.parameters.oneOf"
        - "tools.#.function_declarations.#.parameters.allOf"
EOF
}

write_cli_wrapper() {
  local target="$1"
  local binary_path="$2"

  cat > "$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec "$binary_path" "\$@"
EOF
  chmod 755 "$target"
}

write_start_wrapper() {
  local target="$1"
  local binary_path="$2"
  local config_path="$3"

  cat > "$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec "$binary_path" -config "$config_path" "\$@"
EOF
  chmod 755 "$target"
}

write_login_wrapper() {
  local target="$1"
  local binary_path="$2"
  local login_flag="$3"
  local config_path="$4"

  cat > "$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec "$binary_path" -config "$config_path" $login_flag "\$@"
EOF
  chmod 755 "$target"
}

write_cpaq_wrapper() {
  local target="$1"
  local binary_path="$2"
  local config_path="$3"
  local key_file="$4"

  cat > "$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail

CONFIG_PATH="\${CPAQ_CONFIG_PATH:-$config_path}"
KEY_FILE="\${CPAQ_MANAGEMENT_KEY_FILE:-$key_file}"
BASE_URL="\${CPAQ_BASE_URL:-}"

if [ ! -x "$binary_path" ]; then
  echo "cpaq binary not found at $binary_path" >&2
  exit 1
fi

if [ ! -f "\$KEY_FILE" ]; then
  echo "management key file not found at \$KEY_FILE" >&2
  exit 1
fi

if [ -z "\$BASE_URL" ]; then
  PORT="\$(sed -n 's/^port:[[:space:]]*//p' "\$CONFIG_PATH" | head -n 1 | tr -d '\"' | tr -d '\r' || true)"
  if [ -z "\$PORT" ]; then
    PORT="8318"
  fi
  BASE_URL="http://127.0.0.1:\$PORT"
fi

MANAGEMENT_KEY="\$(tr -d '\r\n' < "\$KEY_FILE")"

if [ -z "\$MANAGEMENT_KEY" ]; then
  echo "management key file is empty: \$KEY_FILE" >&2
  exit 1
fi

exec "$binary_path" --cpa-base-url "\$BASE_URL" -k "\$MANAGEMENT_KEY" "\$@"
EOF
  chmod 755 "$target"
}

write_service_unit() {
  local target="$1"
  local binary_path="$2"
  local config_path="$3"

  mkdir -p "$(dirname "$target")"
  cat > "$target" <<EOF
[Unit]
Description=CLIProxyAPI User Service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$binary_path -config $config_path
Restart=always
RestartSec=5
WorkingDirectory=$APP_DIR

[Install]
WantedBy=default.target
EOF
}

write_systemd_install_wrapper() {
  local target="$1"
  local service_path="$2"

  cat > "$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail

SERVICE_PATH="$service_path"

command -v systemctl >/dev/null 2>&1 || {
  echo "systemctl not found" >&2
  exit 1
}

systemctl --user daemon-reload
systemctl --user enable --now "$(basename "$SERVICE_PATH")"
systemctl --user status "$(basename "$SERVICE_PATH")" --no-pager || true
EOF
  chmod 755 "$target"
}

write_systemd_uninstall_wrapper() {
  local target="$1"
  local service_path="$2"

  cat > "$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="$(basename "$service_path")"

if command -v systemctl >/dev/null 2>&1; then
  systemctl --user disable --now "\$SERVICE_NAME" >/dev/null 2>&1 || true
  systemctl --user daemon-reload >/dev/null 2>&1 || true
fi
EOF
  chmod 755 "$target"
}

write_systemd_control_wrapper() {
  local target="$1"
  local verb="$2"
  local service_path="$3"

  cat > "$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec systemctl --user $verb "$(basename "$service_path")" "\$@"
EOF
  chmod 755 "$target"
}

write_systemd_logs_wrapper() {
  local target="$1"
  local service_path="$2"

  cat > "$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec journalctl --user -u "$(basename "$service_path")" -n 200 -f "\$@"
EOF
  chmod 755 "$target"
}

config_has_bcrypt_secret() {
  local config_path="$1"
  grep -Eq '^[[:space:]]*secret-key:[[:space:]]*"\$2[aby]\$' "$config_path"
}

bootstrap_management_secret() {
  local binary_path="$1"
  local config_path="$2"
  local bootstrap_log="$TMP_DIR/bootstrap.log"
  local pid=""

  if config_has_bcrypt_secret "$config_path"; then
    return
  fi

  log "Bootstrapping CLIProxyAPI once to hash the management secret"
  "$binary_path" -config "$config_path" >"$bootstrap_log" 2>&1 &
  pid=$!

  for _ in $(seq 1 20); do
    if config_has_bcrypt_secret "$config_path"; then
      break
    fi
    if ! kill -0 "$pid" >/dev/null 2>&1; then
      break
    fi
    sleep 1
  done

  kill "$pid" >/dev/null 2>&1 || true
  wait "$pid" 2>/dev/null || true

  if config_has_bcrypt_secret "$config_path"; then
    log "Management secret hashed successfully"
  else
    log "Bootstrap hash step did not complete; first manual start may still be needed"
    if [ -s "$bootstrap_log" ]; then
      sed -n '1,20p' "$bootstrap_log" >&2 || true
    fi
  fi
}

install_release_binary() {
  local repo="$1"
  local asset_name="$2"
  local output_path="$3"
  local extracted_name="$4"
  local asset_url

  asset_url="$(fetch_release_asset_url "$repo" "$asset_name")"
  log "Downloading $repo asset $asset_name"
  curl -fsSL "$asset_url" -o "$TMP_DIR/$asset_name"
  tar -xzf "$TMP_DIR/$asset_name" -C "$TMP_DIR"
  install -m 755 "$TMP_DIR/$extracted_name" "$output_path"
}

main() {
  require_cmd curl
  require_cmd tar
  require_cmd python3
  require_cmd openssl
  require_cmd awk

  [ "$(uname -s)" = "Linux" ] || fail "This installer supports Linux only."

  local arch
  local management_key
  local cli_version
  local cpaq_version

  arch="$(detect_arch)"
  management_key="$(random_secret)"

  mkdir -p "$APP_DIR" "$BIN_DIR" "$CONFIG_DIR"
  mkdir -p "$SYSTEMD_USER_DIR"
  chmod 700 "$CONFIG_DIR"

  cli_version="$(fetch_release_version "$CLIPROXYAPI_REPO")"
  cpaq_version="$(fetch_release_version "$CPAQ_REPO")"

  install_release_binary \
    "$CLIPROXYAPI_REPO" \
    "CLIProxyAPI_${cli_version}_linux_${arch}.tar.gz" \
    "$APP_DIR/cli-proxy-api" \
    "cli-proxy-api"

  install_release_binary \
    "$CPAQ_REPO" \
    "CLIProxyAPI-Quota-Inspector_${cpaq_version}_linux_${arch}.tar.gz" \
    "$APP_DIR/cpa-quota-inspector" \
    "cpa-quota-inspector"

  if [ ! -f "$CONFIG_DIR/management.key" ]; then
    printf '%s\n' "$management_key" > "$CONFIG_DIR/management.key"
    chmod 600 "$CONFIG_DIR/management.key"
    log "Generated management key at $CONFIG_DIR/management.key"
  else
    management_key="$(tr -d '\r\n' < "$CONFIG_DIR/management.key")"
    log "Keeping existing management key at $CONFIG_DIR/management.key"
  fi

  if [ "$FORCE_CONFIG" = "1" ] && [ -f "$CONFIG_PATH" ]; then
    cp -f "$CONFIG_PATH" "$CONFIG_PATH.bak.$(date +%Y%m%d-%H%M%S)"
    log "Backed up existing config before overwrite"
  fi

  if [ ! -f "$CONFIG_PATH" ] || [ "$FORCE_CONFIG" = "1" ]; then
    render_config "$CONFIG_PATH" "$DEFAULT_API_KEY" "$management_key" "$DEFAULT_PORT"
    chmod 600 "$CONFIG_PATH"
    cp -f "$CONFIG_PATH" "$CONFIG_DIR/config.yaml"
    chmod 600 "$CONFIG_DIR/config.yaml"
    log "Wrote template config to $CONFIG_PATH"
    bootstrap_management_secret "$APP_DIR/cli-proxy-api" "$CONFIG_PATH"
    cp -f "$CONFIG_PATH" "$CONFIG_DIR/config.yaml"
    chmod 600 "$CONFIG_DIR/config.yaml"
  else
    cp -f "$CONFIG_PATH" "$CONFIG_DIR/config.yaml"
    chmod 600 "$CONFIG_DIR/config.yaml"
    log "Keeping existing config at $CONFIG_PATH"
  fi

  write_cli_wrapper "$BIN_DIR/cliproxyapi" "$APP_DIR/cli-proxy-api"
  write_start_wrapper "$BIN_DIR/cliproxyapi-start" "$APP_DIR/cli-proxy-api" "$CONFIG_PATH"
  write_login_wrapper "$BIN_DIR/cliproxyapi-codex-login" "$APP_DIR/cli-proxy-api" "-codex-login" "$CONFIG_PATH"
  write_login_wrapper "$BIN_DIR/cliproxyapi-claude-login" "$APP_DIR/cli-proxy-api" "-claude-login" "$CONFIG_PATH"
  write_login_wrapper "$BIN_DIR/cliproxyapi-antigravity-login" "$APP_DIR/cli-proxy-api" "-antigravity-login" "$CONFIG_PATH"
  write_login_wrapper "$BIN_DIR/cliproxyapi-gemini-login" "$APP_DIR/cli-proxy-api" "-login" "$CONFIG_PATH"
  write_cpaq_wrapper "$BIN_DIR/cpaq" "$APP_DIR/cpa-quota-inspector" "$CONFIG_PATH" "$CONFIG_DIR/management.key"
  write_service_unit "$SERVICE_PATH" "$APP_DIR/cli-proxy-api" "$CONFIG_PATH"
  write_systemd_install_wrapper "$BIN_DIR/cliproxyapi-service-install" "$SERVICE_PATH"
  write_systemd_uninstall_wrapper "$BIN_DIR/cliproxyapi-service-uninstall" "$SERVICE_PATH"
  write_systemd_control_wrapper "$BIN_DIR/cliproxyapi-service-start" "start" "$SERVICE_PATH"
  write_systemd_control_wrapper "$BIN_DIR/cliproxyapi-service-stop" "stop" "$SERVICE_PATH"
  write_systemd_control_wrapper "$BIN_DIR/cliproxyapi-service-restart" "restart" "$SERVICE_PATH"
  write_systemd_control_wrapper "$BIN_DIR/cliproxyapi-service-status" "status --no-pager" "$SERVICE_PATH"
  write_systemd_logs_wrapper "$BIN_DIR/cliproxyapi-service-logs" "$SERVICE_PATH"

  ensure_path_line

  log "CLIProxyAPI version: $cli_version"
  log "CLIProxyAPI-Quota-Inspector version: $cpaq_version"
  log "Install root: $INSTALL_ROOT"
  log "Config path: $CONFIG_PATH"
  log "OAuth/auth dir: $CONFIG_DIR"
  log "Commands:"
  log "  cliproxyapi-start"
  log "  cliproxyapi-codex-login"
  log "  cliproxyapi-claude-login"
  log "  cliproxyapi-antigravity-login"
  log "  cliproxyapi-gemini-login"
  log "  cpaq"
  log "  cliproxyapi-service-install"
  log "  cliproxyapi-service-uninstall"
  log "  cliproxyapi-service-start"
  log "  cliproxyapi-service-stop"
  log "  cliproxyapi-service-restart"
  log "  cliproxyapi-service-status"
  log "  cliproxyapi-service-logs"
}

main "$@"
